---
- name: Configure Nginx Web Server
  hosts: web 
  become: yes  

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create custom index.html
      copy:
        content: |
          <html>
            <body>
              <h1>Welcome to {{ ansible_hostname }}!</h1>
              <p>Configured by Ansible.</p>
            </body>
          </html>
        dest: /var/www/html/index.html
        mode: 0644

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes